name             'querycasts-lab'
maintainer       'Jimmy Cuadra'
maintainer_email 'jimmy@jimmycuadra.com'
license          'MIT'
description      'Provisions the Querycasts Lab'
long_description 'Provisions the Querycasts Lab'
version          '0.0.1'
